In [1]:
import time
import numpy as np
from Activation import activeFunc
from Layer_amir_29_12 import Layer
from Tests import sets
from Tests import Set
from prettytable import PrettyTable
        
class NeuralNetwork():
    def __init__(self,init_range,eta):
        self.init_range = init_range
        self.layers = []
        self.eta = eta
        self.errors = 0
        
    def add_layer(self,insize,outsize,actvfunc='Sigmoid'):
        self.layers.append(Layer(insize, outsize , activeFunc(actvfunc) , self.init_range))
    
    def forward_pass(self,inputdata):
        input_x = inputdata
        for x in self.layers:
            x.calc(input_x)
            input_x = x.out
    def back_propogation(self,x,y,batchsize,iter):
        L = len(self.layers)
        self.layers[-1].delta = (y - self.layers[-1].out)
        self.layers[-1].d_o_sum = self.layers[-1].d_o_sum + np.dot(self.layers[L-2].out[:,None],self.layers[-1].delta[None,:])
        for l in reversed(range(1,L-1,1)):
            self.layers[l].delta_calc(self.layers[l-1].out ,self.layers[l+1],batchsize)
        self.layers[0].delta_calc(x,self.layers[1],batchsize)
    
    def epoch(self, epochs, batchsize, x_train, y_train, x_test, y_test):
        errvec = np.zeros([1,3])
        self.errors = np.zeros([epochs*batchsize,1])
        iter = 0
        for j in range(epochs):
            for i in range(batchsize):
                self.forward_pass(inputdata = x_train.current())
                errvec = self.layers[-1].out - y_train.current()
                print(self.layers[-1].out)
                print(y_train.current())
                self.errors[iter] = 0.5 * errvec @ errvec.transpose() 
                iter = iter + 1
                x_train.next_entry()
                self.back_propogation(x_train.current(),y_train.current(),batchsize,i)
                #print('-------- w layer 0 ----------')
                #print(self.layers[0].w)
                #print('-------- w layer 1 ----------')
                #print(self.layers[1].w)
                y_train.next_entry()
            #time.sleep(0.07)
                
            for x in self.layers: 
                x.update_w(self.eta)
                #print('1')
                
    def accuracy(self,x_test,y_test):
        correct_answers = 0
        for i in range(y_test.num_of_inputs):
            self.forward_pass(x_test.current())
            vec = self.layers[-1].out
            output1 = np.zeros_like(vec)
            output1[np.argmax(vec)]=1
            if (output1 == y_test.current()).all():
                correct_answers = correct_answers +1
            #print("NN output: ")
            #print(output1)
            #print("Target: ")
            #print(y_test.current())
            x_test.next_entry()
            y_test.next_entry()
        
        print(correct_answers/y_test.num_of_inputs)
    
    def summary(self):
        ## summary table of the NN
        i=0
        t = PrettyTable(['Layer number', 'Output shape', 'ActiveFunc', 'Weights shape'])
        for x in self.layers:
            t.add_row([i, x.outsize, x.actvfunc, x.w.shape])
            i = i+1
        print(t)

Layer version 1.1


In [2]:
x  = NeuralNetwork(0.5,0.2)
x.add_layer(4,3)
x.add_layer(3,3)
from sklearn import datasets
xx,yy = datasets.load_iris(return_X_y=True)
NN = sets(xx,yy,v1=0, v2=0.05)
x_train,x_test,y_train,y_test = NN.return_classes()

In [3]:
x.accuracy(x_test, y_test)
x.epoch(1000,10,x_train,y_train, x_test, y_test)
x.accuracy(x_test,y_test)

0.2894736842105263
[0.56138361 0.52927088 0.41279157]
[0. 1. 0.]
[0.56126297 0.52923914 0.41285566]
[1. 0. 0.]
[0.5612813  0.52924058 0.41284802]
[1. 0. 0.]
[0.56111253 0.52924027 0.41289994]
[0. 0. 1.]
[0.56114486 0.52924471 0.41288893]
[0. 0. 1.]
[0.56144651 0.52929093 0.41274459]
[1. 0. 0.]
[0.56128758 0.52924942 0.41284072]
[1. 0. 0.]
[0.56113456 0.52923942 0.4129036 ]
[0. 0. 1.]
[0.56142377 0.52928033 0.41276866]
[0. 1. 0.]
[0.56138314 0.52927407 0.41278166]
[1. 0. 0.]
[0.53863049 0.40669628 0.37229985]
[0. 1. 0.]
[0.53857589 0.40674194 0.37238262]
[0. 1. 0.]
[0.53870592 0.40667209 0.37224248]
[0. 1. 0.]
[0.53847782 0.40677084 0.37244526]
[1. 0. 0.]
[0.53869755 0.40665159 0.37223113]
[0. 1. 0.]
[0.53855639 0.40673308 0.372368  ]
[1. 0. 0.]
[0.53847935 0.40676979 0.37244832]
[1. 0. 0.]
[0.53868549 0.40667079 0.37225181]
[0. 1. 0.]
[0.53861593 0.40671996 0.37233383]
[1. 0. 0.]
[0.53850045 0.40676137 0.37242584]
[1. 0. 0.]
[0.52407319 0.44102611 0.25317892]
[0. 1. 0.]
[0.52387652 0.4

In [7]:
x.accuracy(x_test,y_test)

0.21052631578947367


In [19]:
j = np.array([0.2,0.3,0,6])

In [36]:
n = np.zeros_like(j)
n[np.argmax(j)] = 1

In [44]:
x.forward_pass(x_test.current)

TypeError: Object arrays are not currently supported