In [1]:
from Activation import activeFunc
from Tests import sets
import numpy as np


In [8]:
class Layer:
    def __init__(self, insize, outsize , actvfunc , init_range, R_min=-1, R_max=1 ):
        ## init_range - the range for the initial w
        ## delta (batch_sizexoutput)
        ## v (1xinput)
        ## w (input x output)
        self.R_min = R_min
        self.R_max = R_max
        self.w = init_range * np.random.uniform(R_min,R_max,[insize , outsize]) ## To-Do initializie weights to R available
        self.insize = insize;
        self.outsize = outsize;
        self.actvfunc = actvfunc
        self.v = 0
        self.out = 0
        self.delta = 0
        self.first_update = True
    
    def calc(self,input1):
        try:
            #input_bias = np.append(input1, [1])
            self.v = input1 @ self.w
            self.out = self.actvfunc.calc(input1 @ self.w)
        except ValueError:
            #input_bias = np.append(input1, [1]).transpose()
            input1 = input1.transpose()
            self.v = input1 @ self.w
            self.out = self.actvfunc.calc(input1 @ self.w)

    def delta_calc(self, layer):
        if self.first_update == True:
            self.delta = np.array(self.actvfunc.derv(self.v)*(layer.delta @ layer.w.transpose()))
            self.delta = self.delta.reshape(1,self.outsize)
            self.first_update = False
        else:
            self.delta = np.append(self.delta, self.actvfunc.derv(self.v)*((layer.delta @ layer.w.transpose())),0)
    
    def update_w(self,eta):
        self.w = self.w +eta*self.out.transpose() @ self.delta.transpose()
        self.delta = 0
        self.first_update = True

In [9]:
x = Layer(insize=4, outsize=4, actvfunc=activeFunc('tanh'),init_range=1) 
y = Layer(insize=4, outsize=2, actvfunc=activeFunc('tanh'),init_range=1) 

In [10]:
x.calc(np.array([1, 2, 3, 4]))

In [11]:
x.w

array([[-0.86730654, -0.67841183,  0.15889415,  0.59780307],
       [ 0.52165584,  0.67728055,  0.88230074, -0.28897256],
       [-0.03003749,  0.63918231, -0.43366278, -0.24956869],
       [-0.51814893, -0.61469604,  0.74529409,  0.95134967]])

In [12]:
y.delta = np.ones([1,2])

In [13]:
x.delta_calc(y)

In [14]:
x.delta.shape

(1, 4)

In [138]:
x.update_w(0.1)

In [139]:
x.w

array([[-0.9312979 ,  1.00038791, -0.7809241 ,  0.66531372],
       [-0.32726776, -0.97996147, -0.40405448, -0.31810636],
       [ 0.56440571,  0.18961784, -0.75942415,  0.80033147],
       [-0.18810492, -0.27101712, -0.4741923 ,  0.95124151]])

In [9]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(9.0).reshape((3, 3))/2

In [11]:
x1

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [12]:
x2

array([[ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ]])

In [13]:
x1*x2

array([[  0. ,   0.5,   2. ],
       [  4.5,   8. ,  12.5],
       [ 18. ,  24.5,  32. ]])

In [3]:
x = [1, 2, 3]

In [6]:
y = iter(x)

In [8]:
next(y)

1

In [5]:
y = np.ones([2, 2])

In [20]:
x = np.ones([2,1])

In [21]:
x

array([[ 1.],
       [ 1.]])

In [22]:
z = np.append(y,x,1)

In [23]:
z

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])